# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: poetry
      extras: ["dev"] # Optional: install dev dependencies too
  system_packages: false

sphinx:
  configuration: docs/conf.py

formats: [] # skip PDF/epub builds unless needed
